version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-mastery-app
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - APP_SERVER_HTTP_PORT=8081
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./config.yaml:/root/config.yaml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge